### PR TITLE
ver 3.30.20 release

### PR DESCRIPTION
**Pull request by nschindler-noaa**
Added .zip file

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
Great @nschindler-noaa. Let me know if you need help creating a tag or an official release for this repository.

**Comment by nschindler-noaa** [comment]
I've created a release v3.30.20.00 for the SSI.

**Comment by nschindler-noaa** [comment]
And checked the box on #352

**Comment by kellijohnson-NOAA** [comment]
Great!

**Pull request merged**
